spring:
  profiles.active: development
  jpa.properties.jadira.usertype.autoRegisterUserTypes: true

info.build:
  name: ${name}
  version: ${version}

logging.level.org.ceva24: TRACE

security.basic.realm: Twitter Bot

---

spring:
  profiles: development
  datasource.url: jdbc:h2:mem:testdb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  h2.console.enabled: true

security.user:
  name: user
  password: pass

org.ceva24.twitter-bot:
  tweet.quiet-period.seconds: 10
  tweet.downtime-period.seconds: 20
  twitter:
    consumer-key:
    consumer-secret:
    access-token:
    access-token-secret:

---

spring:
  profiles: test
  profiles.include: development
  datasource.initialize: false

---

spring:
  profiles: production
  datasource:
    initialize: false
    initial-size: 1
    max-active: 1
    max-idle: 1
    min-idle: 1
    max-wait: 10000
    test-on-borrow: true
    test-on-connect: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 300000

security.require-ssl: true

org.ceva24.twitter-bot.tweet:
  quiet-period.seconds: 84600 # 23.5 hours
  downtime-period.seconds: 2419200 # 1 month