# fill in production details and include as externalised configuration in classpath

spring.profiles.active: production

---

spring:
  profiles: production
  datasource:
    url:
    username:
    password:
    validation-query:
  jpa:
    properties.hibernate.default_schema:
    database-platform:

security.user:
  name:
  password:

logging.file:

org.ceva24.twitter-bot.twitter:
  consumer-key:
  consumer-secret:
  access-token:
  access-token-secret:
